### ISSUE TITLE
Is it possible to use `useContext` function instead of Consumer?

### ISSUE THREAD

**Issue by molefrog** [bespoyasov/you-really-dont-need-redux-now#1]
Hey, I was just passing by 👋 

Saw your article and the code — looks cool! I was recently thinking about the way React changed during the last couple of years, and it indeed looks like with these new APIs Redux becomes redundant in some sense. 

One question I had however is can we use the `useContext` hook instead of `Consumer` component?
What I mean is replacing this:
```js
const Display = () => (
  <StoreContext.Consumer>
    {({state, dispatch}) => ... }
  </StoreContext.Consumer>
```

with this:
```js
import React, { useContext } from 'react'

const Display = () => {
  const { state, dispatch } = useContext(StoreContext)

  return (
    <footer>
      <p>Another component knows that counter equals to {state.counter} as well!</p>
      
      <p>
        It even can 
        <button 
          onClick={() => dispatch(reset())}>
          reset the coutner</button>
      </p>
    </footer>
  )
}
```

P.S. Haven't tested the code. 
Cheers, Alex.

**Comment by bespoyasov** [comment]
You are totally right! :–)

I don't know how I missed that part. Fixed now!
Thanks!
